project:
  type: website
  output-dir: "docs"
  render:
    - "*.qmd"

website:
  title: "Quality and Outcomes Framework (QOF)"
  favicon: "coffee-cup.svg"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: analyses_listing.qmd
        text: Analyses
    right:
      - icon: git
        href: https://github.com/rmgpanw/qof
        aria-label: github_gitlab
  repo-url: https://github.com/rmgpanw/qof
  repo-actions: [edit, issue]
  repo-branch: main
  reader-mode: true



format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    code-fold: true
    code-link: true
    code-tools:
      source: repo
      toggle: true
      caption: Code

editor: source
