---
title: "Welcome"
editor_options: 
  chunk_output_type: console
---

## About QOF

The Quality and Outcomes Framework (QOF) is a system used in the NHS to financially incentivize General Practitioners (GPs) in the UK for providing high-quality care to patients. Introduced in 2004, QOF is a voluntary program that rewards practices based on their performance in key areas of patient care, such as chronic disease management, public health, and preventative measures.

GPs accumulate points based on meeting specific indicators, which are tied to evidence-based best practices for conditions like diabetes, hypertension, asthma, and mental health. These indicators are tracked using QOF codes, which are clinical codes (often from the Read or SNOMED CT coding systems) assigned to specific activities or interventions. Accurate coding ensures that GPs receive financial remuneration based on the points earned for achieving set targets, encouraging better outcomes for patients and supporting data-driven improvements in healthcare delivery.

## Analysis pipeline

Re-run the analysis pipeline by running `targets::tar_make()`

```{r tar-visnetwork}
targets::tar_visnetwork(targets_only = TRUE,
                        callr_arguments = list(show = FALSE))
```
